[workspace]
members = [
    "crates/client",
    "crates/shared",
    "crates/launcher",
    "crates/server",
    "crates/llm",
    "crates/reinforcement_learning",
]
resolver = "2"
default-members = ["crates/launcher"]
lints = {}


[workspace.dependencies]
avian3d = { version = "0.4", default-features = true, features = ["serialize"] }

bevy = { version = "0.17.2" }
bevy-inspector-egui = "0.34.0"
bevy_egui = { version = "0.38.0" }
serde = "1.0.228"
lightyear = { git = "https://github.com/cBournhonesque/lightyear", branch = "main", default-features = true, features = [
    "netcode",
    "leafwing",
    "avian3d",
    "udp",
    "crossbeam",
    "prediction",
    "interpolation",
] }

leafwing-input-manager = { version = "0.18.0" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.bevy_dylib]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
