[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
server = { path = "../server" }
lightyear.workspace = true
bevy-inspector-egui.workspace = true
leafwing-input-manager.workspace = true
avian3d.workspace = true
bevy.workspace = true
